### ISSUE TITLE
prepare.py 

### ISSUE THREAD

**Issue by hj950815** [lfz/DSB2017#104]
Hi,
I meet some problems with prepare.py .Just like this
starting preprocessing
Traceback (most recent call last):
  File "prepare.py", line 374, in <module>
    full_prep(step1=True,step2=True)
  File "prepare.py", line 181, in full_prep
    _=pool.map(partial_savenpy,range(N))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
 Can you give  me some advice ? Thank you for your help! @lfz

**Comment by zhan-zhang** [comment]
I would suggest you to unwrap the map function to see where the problem really happened

**Comment by anruoxi123** [comment]
Have you solved the problem? How is it solved?

**Comment by chenggangdu** [comment]
In prepare.py, change line188  to 'extramask = dilatedMask ^ Mask'
