### ISSUE TITLE
TypeError: Only 2-D images supported.

### ISSUE THREAD

**Issue by mowen9** [lfz/DSB2017#57]
Testing:
ubuntu@ubuntu-ESC1000-G2:~/04Lung/DSB2017-master$ python main.py 
starting preprocessing
bug in ac7493533e667b077b7180642fb1dc4d
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    use_existing=config_submit['use_exsiting_preprocessing'])
  File "/home/ubuntu/04Lung/DSB2017-master/preprocessing/full_prep.py", line 124, in full_prep
    _=pool.map(partial_savenpy,range(N))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
TypeError: Only 2-D images supported.

config_submit.py:
config = {'datapath':'/home/ubuntu/04Lung/DSB2017-master/stage2/stage2',
          'preprocess_result_path':'./prep_result/',
          'outputfile':'prediction.csv',
          
          'detector_model':'net_detector',
         'detector_param':'./model/detector.ckpt',
         'classifier_model':'net_classifier',
         'classifier_param':'./model/classifier.ckpt',
         'n_gpu':8,
         'n_worker_preprocessing':None,
         'use_exsiting_preprocessing':False,
         'skip_preprocessing':False,
         'skip_detect':False}

What's wrong?

**Comment by lfz** [comment]
this error is wrapped inside the pool function, so I do not know where exactly is the error.

It seems that some function like imresize gives the error, I suggest you to check the versions of scipy or other related packages
