### ISSUE TITLE
关于detector的train

### ISSUE THREAD

**Issue by Carl-Lei** [lfz/DSB2017#94]
我在python3.6训练时出现错误
Traceback (most recent call last):
  File "main.py", line 349, in <module>
    main()
  File "main.py", line 168, in main
    train(train_loader, net, loss, epoch, optimizer, get_lr, args.save_freq, save_dir)
  File "main.py", line 180, in train
    for i, (data, target, coord) in enumerate(data_loader):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 247, in __init__
    self._put_indices()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 295, in _put_indices
    indices = next(self.sample_iter, None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\sampler.py", line 138, in __iter__
    for idx in self.sampler:
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\sampler.py", line 51, in __iter__
    return iter(torch.randperm(len(self.data_source)).tolist())
TypeError: 'float' object cannot be interpreted as an integer
不知道这里的‘float’指的时哪个变量？这种情况下，怎么改啊？

**Comment by Carl-Lei** [comment]
我把第99行的net = DataParallel(net)注释掉还是不行啊，还是报同样的错误

**Comment by Carl-Lei** [comment]
我把第99行的net = DataParallel(net)注释掉，还是不行啊，报同样的错误

**Comment by Carl-Lei** [comment]
@lfz

**Comment by Carl-Lei** [comment]
这个问题好像解决了。是因为在DataBowl3Detector的类里面
    def __len__(self):
        if self.phase == 'train':
            return len(self.bboxes)/(1-self.r_rand)
这里是要return一个整数吗？ @lfz

**Comment by Carl-Lei** [comment]
@lfz 
这一句为什么会报错啊？input_size=(128,128,128), stride=4
这个取余的判断怎么会是False呢？
Traceback (most recent call last):
  File "D:/mydsb/dsb_test/training/detector/main.py", line 349, in <module>
    main()
  File "D:/mydsb/dsb_test/training/detector/main.py", line 168, in main
    train(train_loader, net, loss, epoch, optimizer, get_lr, args.save_freq, save_dir)
  File "D:/mydsb/dsb_test/training/detector/main.py", line 180, in train
    for i, (data, target, coord) in enumerate(data_loader):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 272, in __next__
    return self._process_next_batch(batch)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\mydsb\dsb_test\training\detector\data.py", line 96, in __getitem__
    label = self.label_mapping(sample.shape[1:], target, bboxes)
  File "D:\mydsb\dsb_test\training\detector\data.py", line 273, in __call__
    assert(int(input_size[i])% stride == 0)
AssertionError

**Comment by shenlinyao** [comment]
```
def len(self):
if self.phase == 'train':
return len(self.bboxes)/(1-self.r_rand)
```
解决了吗，我也有这个问题，我把/改成//，好像也不行

**Comment by Carl-Lei** [comment]
@shenlinyao 我是强行转换为int类型的 return int(len(self.bboxes)/(1-self.r_rand))

**Comment by DaLei001** [comment]
@Carl-Lei 同样遇到了“assert(int(input_size[i])% stride == 0) AssertionError”的问题，请问你解决了这个问题了吗？

**Comment by lihaossu** [comment]
@DaLei001 请问 config里面的'luna_segment':'/work/DataBowl3/luna/seg-lungs-LUNA16/'的路径是什么？需要一些额外的数据吗？还是直接建立一个空的文件？

**Comment by chenggangdu** [comment]
> @DaLei001 请问 config里面的'luna_segment':'/work/DataBowl3/luna/seg-lungs-LUNA16/'的路径是什么？需要一些额外的数据吗？还是直接建立一个空的文件？

这是LUNA的一个文件夹
